/**
 * serve.js Template Generator
 * Creates a self-contained Express server for serving extracted content
 */

import { generateAllMocks } from './mocks/index.js';
import { MIME_TYPES } from './router.js';

/**
 * Generate serve.js content
 * @param {Object} options - Configuration options
 * @param {number} options.port - Server port (default: 3000)
 * @param {string} options.originalUrl - Original extracted URL
 * @param {boolean} options.enableProxy - Enable proxy fallback (default: false)
 * @param {boolean} options.enableCors - Enable CORS headers (default: true)
 * @param {Object} options.mocks - Mock configuration
 * @returns {string} serve.js file content
 */
export function generateServeTemplate(options = {}) {
  const port = options.port || 3000;
  const enableProxy = options.enableProxy || false;
  const enableCors = options.enableCors !== false;
  const mockConfig = options.mocks || { api: true, auth: true, analytics: true };

  // Generate mock scripts
  const mockScripts = generateAllMocks(mockConfig);

  return `#!/usr/bin/env node
/**
 * Visual Cloner - Local Development Server
 * Self-contained Express server for serving extracted content
 *
 * Usage: node serve.js
 *
 * Generated by Visual Cloner
 */

const express = require('express');
const fs = require('fs');
const path = require('path');
const http = require('http');
const https = require('https');

// =============================================================================
// CONFIGURATION
// =============================================================================

const PORT = process.env.PORT || ${port};
const PROXY_ENABLED = ${enableProxy};
const CORS_ENABLED = ${enableCors};

// MIME type mapping
const MIME_TYPES = ${JSON.stringify(MIME_TYPES, null, 2)};

// =============================================================================
// INITIALIZATION
// =============================================================================

const app = express();

// Load URL map
let urlMap = {};
const urlMapPath = path.join(__dirname, 'url-map.json');
if (fs.existsSync(urlMapPath)) {
  urlMap = JSON.parse(fs.readFileSync(urlMapPath, 'utf-8'));
  console.log(\`[Init] Loaded \${Object.keys(urlMap).length} URL mappings\`);
} else {
  console.warn('[Init] No url-map.json found');
}

// Load manifest for original URL info
let manifest = {};
const manifestPath = path.join(__dirname, 'manifest.json');
if (fs.existsSync(manifestPath)) {
  manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf-8'));
}
const ORIGINAL_URL = manifest.url || 'http://localhost';
const originalUrlObj = new URL(ORIGINAL_URL);

// Build lookup tables
const lookup = new Map();
for (const [fullUrl, info] of Object.entries(urlMap)) {
  try {
    const urlObj = new URL(fullUrl);
    const pathWithQuery = urlObj.pathname + urlObj.search;
    const pathOnly = urlObj.pathname;

    if (!lookup.has(pathWithQuery)) {
      lookup.set(pathWithQuery, info);
    }
    if (!lookup.has(pathOnly)) {
      lookup.set(pathOnly, info);
    }
  } catch (e) {
    // Invalid URL, skip
  }
}

// =============================================================================
// RUNTIME MOCKS (Injected into HTML)
// =============================================================================

const RUNTIME_MOCKS = \`${mockScripts.replace(/`/g, '\\`').replace(/\$/g, '\\$')}\`;

// =============================================================================
// HELPER FUNCTIONS
// =============================================================================

function getContentType(filename) {
  const match = filename.match(/\\.[^.]+$/);
  const ext = match ? match[0].toLowerCase() : '';
  return MIME_TYPES[ext] || 'application/octet-stream';
}

function injectMocksIntoHtml(html) {
  // Build config injection
  const configScript = \`
<script>
// Runtime configuration injected by Visual Cloner
window.__EXTRACTED_CONFIG__ = {
  originalOrigin: "\${originalUrlObj.origin}",
  originalHost: "\${originalUrlObj.host}",
  originalProtocol: "\${originalUrlObj.protocol}",
  originalHref: "\${ORIGINAL_URL}"
};
</script>
<script>
\${RUNTIME_MOCKS}
</script>
\`;

  // Find <head> tag and inject
  const headMatch = html.match(/<head[^>]*>/i);
  if (headMatch) {
    const headTag = headMatch[0];
    const headIndex = html.indexOf(headTag);
    const insertPosition = headIndex + headTag.length;
    return html.substring(0, insertPosition) + '\\n' + configScript + html.substring(insertPosition);
  }

  // Fallback: inject before first script
  const scriptMatch = html.match(/<script/i);
  if (scriptMatch) {
    const scriptIndex = html.indexOf(scriptMatch[0]);
    return html.substring(0, scriptIndex) + configScript + '\\n' + html.substring(scriptIndex);
  }

  // Last resort: inject at start of body
  const bodyMatch = html.match(/<body[^>]*>/i);
  if (bodyMatch) {
    const bodyTag = bodyMatch[0];
    const bodyIndex = html.indexOf(bodyTag);
    const insertPosition = bodyIndex + bodyTag.length;
    return html.substring(0, insertPosition) + '\\n' + configScript + html.substring(insertPosition);
  }

  return configScript + html;
}

function proxyRequest(url, res) {
  const protocol = url.startsWith('https') ? https : http;

  console.log(\`[Proxy] Fetching: \${url}\`);

  protocol.get(url, (proxyRes) => {
    const chunks = [];

    proxyRes.on('data', (chunk) => chunks.push(chunk));
    proxyRes.on('end', () => {
      const body = Buffer.concat(chunks);
      const contentType = proxyRes.headers['content-type'] || 'application/octet-stream';

      res.set({
        'Content-Type': contentType,
        'Access-Control-Allow-Origin': '*',
        'Cache-Control': 'public, max-age=31536000'
      });

      res.status(proxyRes.statusCode).send(body);
      console.log(\`[Proxy] Success: \${url} (\${body.length} bytes)\`);
    });
  }).on('error', (err) => {
    console.error(\`[Proxy] Error: \${url} - \${err.message}\`);
    res.status(502).send('Proxy error');
  });
}

// =============================================================================
// MIDDLEWARE
// =============================================================================

// CORS middleware
if (CORS_ENABLED) {
  app.use((req, res, next) => {
    res.set({
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS',
      'Access-Control-Allow-Headers': '*'
    });

    if (req.method === 'OPTIONS') {
      return res.status(200).end();
    }

    next();
  });
}

// Request logging
app.use((req, res, next) => {
  const start = Date.now();
  res.on('finish', () => {
    const duration = Date.now() - start;
    console.log(\`[\${res.statusCode}] \${req.method} \${req.url} (\${duration}ms)\`);
  });
  next();
});

// =============================================================================
// ROUTES
// =============================================================================

// Status endpoint
app.get('/__status__', (req, res) => {
  res.json({
    status: 'running',
    originalUrl: ORIGINAL_URL,
    resourceCount: Object.keys(urlMap).length,
    proxyEnabled: PROXY_ENABLED
  });
});

// Serve index.html with injected mocks
app.get(['/', '/index.html'], (req, res) => {
  const indexPath = path.join(__dirname, 'index.html');

  if (!fs.existsSync(indexPath)) {
    return res.status(404).send('index.html not found');
  }

  let html = fs.readFileSync(indexPath, 'utf-8');
  html = injectMocksIntoHtml(html);

  res.set('Content-Type', 'text/html; charset=utf-8');
  res.send(html);
});

// Serve mapped resources
app.get('*', (req, res, next) => {
  const requestPath = req.path;
  const requestUrl = req.url;

  // Look up in URL map
  const cached = lookup.get(requestUrl) || lookup.get(requestPath);

  if (cached) {
    const filePath = path.join(__dirname, cached.localFile);

    if (fs.existsSync(filePath)) {
      const contentType = cached.contentType || getContentType(cached.localFile);
      let content = fs.readFileSync(filePath);

      // Inject mocks into HTML files
      if (contentType.includes('text/html')) {
        content = injectMocksIntoHtml(content.toString('utf-8'));
      }

      res.set({
        'Content-Type': contentType,
        'Cache-Control': 'public, max-age=31536000'
      });

      return res.send(content);
    }
  }

  // Try static file from resources directory
  const resourcePath = path.join(__dirname, 'resources', requestPath);
  if (fs.existsSync(resourcePath) && fs.statSync(resourcePath).isFile()) {
    const contentType = getContentType(resourcePath);

    res.set({
      'Content-Type': contentType,
      'Cache-Control': 'public, max-age=31536000'
    });

    return res.sendFile(resourcePath);
  }

  next();
});

// Proxy fallback (if enabled)
app.use((req, res, next) => {
  if (PROXY_ENABLED) {
    const fullUrl = originalUrlObj.origin + req.url;
    return proxyRequest(fullUrl, res);
  }
  next();
});

// SPA fallback - serve index.html for non-file routes
app.use((req, res, next) => {
  if (!req.path.includes('.')) {
    const indexPath = path.join(__dirname, 'index.html');

    if (fs.existsSync(indexPath)) {
      let html = fs.readFileSync(indexPath, 'utf-8');
      html = injectMocksIntoHtml(html);

      res.set('Content-Type', 'text/html; charset=utf-8');
      return res.send(html);
    }
  }
  next();
});

// 404 handler
app.use((req, res) => {
  console.log(\`[404] Not found: \${req.url}\`);
  res.status(404).send('Not found');
});

// Error handler
app.use((err, req, res, next) => {
  console.error('[Error]', err);
  res.status(500).send('Internal server error');
});

// =============================================================================
// START SERVER
// =============================================================================

app.listen(PORT, () => {
  console.log('');
  console.log('='.repeat(60));
  console.log('  VISUAL CLONER SERVER');
  console.log('='.repeat(60));
  console.log('');
  console.log(\`  URL:          http://localhost:\${PORT}\`);
  console.log(\`  Original:     \${ORIGINAL_URL}\`);
  console.log(\`  Resources:    \${Object.keys(urlMap).length}\`);
  console.log(\`  Proxy:        \${PROXY_ENABLED ? 'Enabled' : 'Disabled'}\`);
  console.log(\`  Status:       http://localhost:\${PORT}/__status__\`);
  console.log('');
  console.log('  Press Ctrl+C to stop');
  console.log('');
});
`;
}

/**
 * Generate package.json for the served site
 * @returns {string} package.json content
 */
export function generatePackageJson() {
  return JSON.stringify({
    name: "extracted-site",
    version: "1.0.0",
    description: "Extracted website served by Visual Cloner",
    type: "commonjs",
    main: "serve.js",
    scripts: {
      start: "node serve.js",
      serve: "node serve.js"
    },
    dependencies: {
      express: "^4.18.2"
    }
  }, null, 2);
}

/**
 * Generate the serve.js template as a stringified template function
 * (For cases where the template needs to be embedded)
 * @returns {string} Template function as string
 */
export function getTemplateFunction() {
  return generateServeTemplate.toString();
}

export default {
  generateServeTemplate,
  generatePackageJson,
  getTemplateFunction
};
