/**
 * Server Template Generator
 * Generates a self-contained serve.js for extracted sites with runtime patching
 */

export function generateServer(options = {}) {
  const port = options.port || 3333;
  const proxyEnabled = options.proxy !== false;
  const logLevel = options.logLevel || 'info';

  return `#!/usr/bin/env node
/**
 * Local Server for Extracted Site
 * Generated by Visual Cloner with Runtime Patching
 */

import http from 'http';
import https from 'https';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PORT = ${port};
const PROXY_ENABLED = ${proxyEnabled};
const LOG_LEVEL = '${logLevel}';

// Logging function
function log(level, message) {
  const levels = { error: 0, warn: 1, info: 2, debug: 3 };
  const configLevel = levels[LOG_LEVEL] || 2;
  const msgLevel = levels[level] || 2;

  if (msgLevel <= configLevel) {
    console.log(message);
  }
}

// Statistics
const stats = {
  startTime: Date.now(),
  hits: 0,
  misses: 0,
  proxied: 0,
  patched: 0,
};

// Load manifest
const manifest = JSON.parse(fs.readFileSync(path.join(__dirname, 'manifest.json'), 'utf-8'));
const ORIGINAL_URL = manifest.url;
const originalUrlObj = new URL(ORIGINAL_URL);

// Load URL map
const urlMap = JSON.parse(fs.readFileSync(path.join(__dirname, 'url-map.json'), 'utf-8'));

// Build efficient lookup by pathname (prefer first match)
const lookup = {};
for (const [fullUrl, info] of Object.entries(urlMap)) {
  try {
    const urlObj = new URL(fullUrl);
    const pathWithQuery = urlObj.pathname + urlObj.search;
    const pathOnly = urlObj.pathname;

    // Store with query params (higher priority)
    if (!lookup[pathWithQuery]) {
      lookup[pathWithQuery] = info;
    }
    // Store without query params (fallback)
    if (!lookup[pathOnly]) {
      lookup[pathOnly] = info;
    }
  } catch (e) {
    // Invalid URL, skip
  }
}

// ============================================================================
// RUNTIME PATCHING SYSTEM
// ============================================================================

// Patcher Interface
class IPatcher {
  constructor(name, description) {
    this.name = name;
    this.description = description;
  }
  shouldApply(content, filename) {
    throw new Error('IPatcher.shouldApply() must be implemented');
  }
  apply(content) {
    throw new Error('IPatcher.apply() must be implemented');
  }
  getPatterns() {
    return [];
  }
}

class PatchResult {
  constructor(name, count, examples = []) {
    this.name = name;
    this.count = count;
    this.examples = examples;
  }
}

// Photopea Patcher
class PhotopeaPatcher extends IPatcher {
  constructor() {
    super('photopea', 'Photopea-specific domain bypass patches');
  }

  shouldApply(content, filename) {
    const isJsExtension = filename.endsWith('.js');
    const hasJsContent = content.includes('function') && content.includes('var ');
    const hasPhotopeaPatterns = content.includes('U.alp') ||
                                content.includes('this.aat') ||
                                content.includes('J.adQ') ||
                                content.includes('this.ak6') ||
                                content.includes('photopea.com') ||
                                content.includes('vecpea.com') ||
                                content.includes('jampea.com');

    if (!isJsExtension && !hasJsContent && !hasPhotopeaPatterns) return false;
    return hasPhotopeaPatterns;
  }

  apply(content) {
    const patches = [];
    let modified = content;

    // PATCH 1: U.alp() function - returns 0 for Photopea mode
    const alpResult = this.patchAlpFunction(modified);
    if (alpResult.patched) {
      modified = alpResult.content;
      patches.push(new PatchResult('U.alp', 1, ['U.alp=function(){return 0;}']));
    }

    // PATCH 2: aat flag - keep disabled
    const aatResult = this.patchAatFlag(modified);
    if (aatResult.count > 0) {
      modified = aatResult.content;
      patches.push(new PatchResult('aat-flag', aatResult.count, aatResult.examples));
    }

    // PATCH 3: J.adQ function - replace entire body with return 1
    const adqResult = this.patchAdQFunction(modified);
    if (adqResult.patched) {
      modified = adqResult.content;
      patches.push(new PatchResult('J.adQ', 1, ['J.adQ=function(){return 1;}']));
    }

    // PATCH 4: ak6 flag - prevent it from being set to true
    const ak6Result = this.patchAk6Flag(modified);
    if (ak6Result.count > 0) {
      modified = ak6Result.content;
      patches.push(new PatchResult('ak6-flag', ak6Result.count, ak6Result.examples));
    }

    return { content: modified, patches };
  }

  patchAlpFunction(content) {
    const alpPattern = /U\\.alp\\s*=\\s*function\\s*\\(\\s*\\)\\s*\\{/;
    const match = content.match(alpPattern);
    if (!match) return { content, patched: false };

    const startIndex = match.index + match[0].length;
    let braceCount = 1;
    let endIndex = startIndex;

    while (braceCount > 0 && endIndex < content.length) {
      if (content[endIndex] === '{') braceCount++;
      if (content[endIndex] === '}') braceCount--;
      endIndex++;
    }

    while (endIndex < content.length && content[endIndex] !== ';') {
      endIndex++;
    }
    endIndex++;

    const replacement = 'U.alp=function(){return 0;};';
    const modified = content.substring(0, match.index) +
      replacement +
      content.substring(endIndex);

    return { content: modified, patched: true };
  }

  patchAatFlag(content) {
    let modified = content;
    let count = 0;
    const examples = [];

    const aatPattern = /if\\s*\\(\\s*B\\s*==\\s*0\\s*\\)\\s*this\\.aat\\s*=\\s*!\\s*0\\s*;/g;
    const aatMatches = content.match(aatPattern);

    if (aatMatches && aatMatches.length > 0) {
      modified = modified.replace(aatPattern, 'if(B==0)this.aat=!1;');
      count += aatMatches.length;
      examples.push('if(B==0)this.aat=!0 -> !1');
    } else {
      const alt = /this\\.aat\\s*=\\s*!\\s*0/g;
      const altMatches = content.match(alt);
      if (altMatches) {
        modified = modified.replace(alt, 'this.aat=!1');
        count += altMatches.length;
        examples.push('this.aat=!0 -> !1');
      }
    }

    return { content: modified, count, examples };
  }

  patchAdQFunction(content) {
    const startPattern = /J\\.adQ\\s*=\\s*function\\s*\\(\\s*\\)\\s*\\{/;
    const match = content.match(startPattern);
    if (!match) return { content, patched: false };

    const startIndex = match.index + match[0].length;
    let braceCount = 1;
    let endIndex = startIndex;

    while (braceCount > 0 && endIndex < content.length) {
      if (content[endIndex] === '{') braceCount++;
      if (content[endIndex] === '}') braceCount--;
      endIndex++;
    }

    while (endIndex < content.length && content[endIndex] !== ';') {
      endIndex++;
    }
    endIndex++;

    const modified = content.substring(0, match.index) +
      'J.adQ=function(){return 1;};' +
      content.substring(endIndex);

    return { content: modified, patched: true };
  }

  patchAk6Flag(content) {
    const pattern1 = /if\\s*\\(\\s*\\$\\s*==\\s*0\\s*\\)\\s*this\\.ak6\\s*=\\s*!\\s*0\\s*;/g;
    const matches1 = content.match(pattern1);

    let modified = content;
    let count = 0;
    const examples = [];

    if (matches1 && matches1.length > 0) {
      modified = modified.replace(pattern1, 'if($==0)this.ak6=!1;');
      count += matches1.length;
      examples.push('if($==0)this.ak6=!0 -> !1');
    }

    const pattern2 = /this\\.ak6\\s*=\\s*!\\s*0/g;
    const matches2 = modified.match(pattern2);

    if (matches2 && matches2.length > 0) {
      modified = modified.replace(pattern2, 'this.ak6=!1');
      count += matches2.length;
      examples.push('this.ak6=!0 -> !1');
    }

    return { content: modified, count, examples };
  }

  getPatterns() {
    return [
      { name: 'U.alp', description: 'App mode function - return 0 for Photopea mode' },
      { name: 'aat-flag', description: 'Feature restriction flag - keep disabled' },
      { name: 'J.adQ', description: 'Domain validation function - always return 1' },
      { name: 'ak6-flag', description: 'Feature restriction flag - keep false' },
    ];
  }
}

// Domain Bypass Patcher
class DomainBypassPatcher extends IPatcher {
  constructor() {
    super('domain-bypass', 'Generic domain/license check bypass');
    this.patterns = [
      {
        name: 'hostname-ternary',
        description: 'Ternary operator checking hostname',
        pattern: /var\\s+(\\w+)\\s*=\\s*window\\.location\\.hostname\\.[a-zA-Z]+\\([^)]+\\)\\s*\\?[^;]+:\\s*0/g,
        replace: (match, varName) => {
          if (varName === 'lm') return match;
          return \`var \${varName}=1\`;
        },
      },
      {
        name: 'hostname-equals-ternary',
        description: 'Ternary with hostname equals check',
        pattern: /var\\s+(\\w+)\\s*=\\s*(?:window\\.)?location\\.hostname\\s*===?\\s*["'][^"']+["']\\s*\\?\\s*\\d+\\s*:\\s*0/g,
        replace: (match, varName) => \`var \${varName}=1\`,
      },
      {
        name: 'hostname-includes',
        description: 'Hostname includes check',
        pattern: /if\\s*\\(\\s*(?:window\\.)?location\\.hostname\\.includes\\s*\\([^)]+\\)\\s*\\)/g,
        replace: 'if(true)',
      },
      {
        name: 'origin-not-equals',
        description: 'Origin not equals check',
        pattern: /(?:window\\.)?location\\.origin\\s*!==?\\s*["'][^"']+["']/g,
        replace: 'false',
      },
      {
        name: 'origin-equals',
        description: 'Origin equals check',
        pattern: /(?:window\\.)?location\\.origin\\s*===?\\s*["'][^"']+["']/g,
        replace: 'true',
      },
      {
        name: 'host-check',
        description: 'Host-based validation',
        pattern: /if\\s*\\(\\s*(?:window\\.)?location\\.host\\s*!==?\\s*["'][^"']+["']\\s*\\)/g,
        replace: 'if(false)',
      },
      {
        name: 'navigator-online-false',
        description: 'navigator.onLine check - always online',
        pattern: /if\\s*\\(\\s*!navigator\\.onLine\\s*\\)/g,
        replace: 'if(false)',
      },
      {
        name: 'navigator-online-check',
        description: 'Direct navigator.onLine === false',
        pattern: /navigator\\.onLine\\s*===?\\s*false/g,
        replace: 'false',
      },
      {
        name: 'throw-domain-error',
        description: 'Throw on domain mismatch',
        pattern: /throw\\s+new\\s+Error\\s*\\(\\s*["'][^"']*domain[^"']*["']\\s*\\)/gi,
        replace: '/* domain check bypassed */',
      },
    ];
    this.quickPatterns = [
      /location\\.hostname/,
      /location\\.origin/,
      /location\\.host[^n]/,
      /navigator\\.onLine/,
      /isDomainValid|checkDomain|validateDomain/i,
      /isLicensed|checkLicense/i,
    ];
  }

  shouldApply(content, filename) {
    if (!filename.endsWith('.js')) return false;
    return this.quickPatterns.some(p => p.test(content));
  }

  apply(content) {
    const patches = [];
    let modified = content;

    for (const pattern of this.patterns) {
      const matches = modified.match(pattern.pattern);
      if (matches && matches.length > 0) {
        const count = matches.length;

        if (typeof pattern.replace === 'function') {
          modified = modified.replace(pattern.pattern, pattern.replace);
        } else {
          modified = modified.replace(pattern.pattern, pattern.replace);
        }

        patches.push(new PatchResult(
          pattern.name,
          count,
          matches.slice(0, 2).map(m => m.slice(0, 80))
        ));
      }
    }

    return { content: modified, patches };
  }

  getPatterns() {
    return this.patterns.map(p => ({ name: p.name, description: p.description }));
  }
}

// Initialize patchers
const PATCHERS = [
  new PhotopeaPatcher(),
  new DomainBypassPatcher(),
];

// In-memory patch cache: Map<localFilePath, patchedContent>
const patchCache = new Map();

// Apply patches at startup
log('info', '');
log('info', '='.repeat(60));
log('info', '  APPLYING RUNTIME PATCHES');
log('info', '='.repeat(60));
log('info', '');

const resourcesDir = path.join(__dirname, 'resources');
if (fs.existsSync(resourcesDir)) {
  const jsFiles = fs.readdirSync(resourcesDir).filter(f => f.endsWith('.js'));
  log('info', \`Found \${jsFiles.length} JS files to scan\`);
  log('info', '');

  for (const filename of jsFiles) {
    const filePath = path.join(resourcesDir, filename);
    const content = fs.readFileSync(filePath, 'utf-8');

    let finalContent = content;
    const appliedPatches = [];

    for (const patcher of PATCHERS) {
      if (patcher.shouldApply(finalContent, filename)) {
        const result = patcher.apply(finalContent);
        if (result.patches.length > 0) {
          finalContent = result.content;
          appliedPatches.push({
            patcher: patcher.name,
            patches: result.patches,
          });
        }
      }
    }

    if (appliedPatches.length > 0) {
      const relativePath = 'resources/' + filename;
      patchCache.set(relativePath, finalContent);
      stats.patched++;

      log('info', \`[PATCHED] \${filename}\`);
      for (const ap of appliedPatches) {
        for (const patch of ap.patches) {
          log('info', \`  - \${patch.name}: \${patch.count} change(s)\`);
          if (patch.examples.length > 0) {
            log('debug', \`    Examples: \${patch.examples.join(', ')}\`);
          }
        }
      }
      log('info', '');
    }
  }

  if (stats.patched > 0) {
    log('info', \`Total patched files: \${stats.patched}\`);
  } else {
    log('info', 'No files required patching');
  }
  log('info', '');
  log('info', '='.repeat(60));
  log('info', '');
}

// Load and inject runtime scripts into index.html
let indexHtml = fs.readFileSync(path.join(__dirname, 'index.html'), 'utf-8');
indexHtml = injectRuntimeScripts(indexHtml);

// MIME types
const MIME = {
  '.html': 'text/html; charset=utf-8',
  '.js': 'application/javascript; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.json': 'application/json',
  '.wasm': 'application/wasm',
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.gif': 'image/gif',
  '.webp': 'image/webp',
  '.svg': 'image/svg+xml',
  '.ico': 'image/x-icon',
  '.woff': 'font/woff',
  '.woff2': 'font/woff2',
  '.ttf': 'font/ttf',
  '.otf': 'font/otf',
  '.mp3': 'audio/mpeg',
  '.mp4': 'video/mp4',
  '.webm': 'video/webm',
  '.ogg': 'audio/ogg',
  '.pdf': 'application/pdf',
};

// Inject runtime scripts into HTML
function injectRuntimeScripts(html) {
  // Build URL map for client side
  const clientUrlMap = {};
  for (const [fullUrl, info] of Object.entries(urlMap)) {
    clientUrlMap[fullUrl] = info.localFile;
  }

  const injectionScript = \`
  <script>
  // Runtime configuration injected by Visual Cloner
  window.__EXTRACTED_CONFIG__ = {
    originalOrigin: "\${originalUrlObj.origin}",
    originalHost: "\${originalUrlObj.host}",
    originalProtocol: "\${originalUrlObj.protocol}",
    originalHref: "\${ORIGINAL_URL}"
  };
  window.__URL_MAP__ = \${JSON.stringify(clientUrlMap)};
  </script>
  <script src="/__runtime__/runtime-mock.js"></script>
  <script src="/__runtime__/indexeddb-mock.js"></script>
  <script src="/__runtime__/network-interceptor.js"></script>
\`;

  // Find <head> tag and inject as first child
  const headMatch = html.match(/<head[^>]*>/i);
  if (headMatch) {
    const headTag = headMatch[0];
    const headIndex = html.indexOf(headTag);
    const insertPosition = headIndex + headTag.length;

    return html.substring(0, insertPosition) +
           '\\n' + injectionScript +
           html.substring(insertPosition);
  }

  // Fallback: inject before first script tag
  const scriptMatch = html.match(/<script/i);
  if (scriptMatch) {
    const scriptIndex = html.indexOf(scriptMatch[0]);
    return html.substring(0, scriptIndex) +
           injectionScript + '\\n' +
           html.substring(scriptIndex);
  }

  // Last resort: inject at start of body
  const bodyMatch = html.match(/<body[^>]*>/i);
  if (bodyMatch) {
    const bodyTag = bodyMatch[0];
    const bodyIndex = html.indexOf(bodyTag);
    const insertPosition = bodyIndex + bodyTag.length;

    return html.substring(0, insertPosition) +
           '\\n' + injectionScript +
           html.substring(insertPosition);
  }

  return html;
}

// Proxy request to original server
function proxyRequest(url, res) {
  const protocol = url.startsWith('https') ? https : http;

  log('debug', \`[PROXY] Fetching: \${url}\`);

  protocol.get(url, (proxyRes) => {
    const chunks = [];

    proxyRes.on('data', (chunk) => chunks.push(chunk));
    proxyRes.on('end', () => {
      const body = Buffer.concat(chunks);
      const contentType = proxyRes.headers['content-type'] || 'application/octet-stream';

      // Add CORS headers
      res.writeHead(proxyRes.statusCode, {
        'Content-Type': contentType,
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Methods': '*',
        'Access-Control-Allow-Headers': '*',
        'Cache-Control': 'public, max-age=31536000',
      });

      res.end(body);
      stats.proxied++;

      log('info', \`[PROXY] Success: \${url} (\${body.length} bytes)\`);

      // Optionally cache the proxied response
      cacheProxiedResource(url, body, contentType);
    });
  }).on('error', (err) => {
    log('error', \`[PROXY] Error: \${url} - \${err.message}\`);
    res.writeHead(502);
    res.end('Proxy error');
  });
}

// Cache proxied resource locally
function cacheProxiedResource(url, body, contentType) {
  try {
    const urlObj = new URL(url);
    const ext = path.extname(urlObj.pathname) || getExtFromContentType(contentType);
    const filename = \`proxied-\${Date.now()}\${ext}\`;
    const localFile = \`resources/\${filename}\`;
    const filePath = path.join(__dirname, localFile);

    fs.writeFileSync(filePath, body);

    // Update url-map
    urlMap[url] = {
      localFile,
      contentType,
      size: body.length,
      proxied: true,
    };

    // Update lookup
    lookup[urlObj.pathname + urlObj.search] = urlMap[url];
    lookup[urlObj.pathname] = urlMap[url];

    // Save updated url-map
    fs.writeFileSync(
      path.join(__dirname, 'url-map.json'),
      JSON.stringify(urlMap, null, 2)
    );

    log('debug', \`[CACHE] Saved proxied resource: \${localFile}\`);
  } catch (err) {
    log('error', \`[CACHE] Failed to cache: \${err.message}\`);
  }
}

// Get file extension from content type
function getExtFromContentType(contentType) {
  if (!contentType) return '';

  if (contentType.includes('javascript')) return '.js';
  if (contentType.includes('css')) return '.css';
  if (contentType.includes('html')) return '.html';
  if (contentType.includes('json')) return '.json';
  if (contentType.includes('wasm')) return '.wasm';
  if (contentType.includes('png')) return '.png';
  if (contentType.includes('jpeg') || contentType.includes('jpg')) return '.jpg';
  if (contentType.includes('gif')) return '.gif';
  if (contentType.includes('webp')) return '.webp';
  if (contentType.includes('svg')) return '.svg';
  if (contentType.includes('woff2')) return '.woff2';
  if (contentType.includes('woff')) return '.woff';

  return '';
}

// Create server
http.createServer((req, res) => {
  // CORS preflight
  if (req.method === 'OPTIONS') {
    res.writeHead(200, {
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Methods': '*',
      'Access-Control-Allow-Headers': '*',
    });
    return res.end();
  }

  const reqPath = req.url.split('?')[0];

  // Status endpoint
  if (reqPath === '/__status__') {
    const uptime = Math.floor((Date.now() - stats.startTime) / 1000);
    const status = {
      status: 'running',
      uptime,
      resourcesCount: Object.keys(urlMap).length,
      patched: stats.patched,
      hits: stats.hits,
      misses: stats.misses,
      proxied: stats.proxied,
      originalUrl: ORIGINAL_URL,
      proxyEnabled: PROXY_ENABLED,
    };

    res.writeHead(200, {
      'Content-Type': 'application/json',
      'Access-Control-Allow-Origin': '*',
    });
    return res.end(JSON.stringify(status, null, 2));
  }

  // Serve runtime scripts
  if (reqPath.startsWith('/__runtime__/')) {
    const runtimeFile = reqPath.replace('/__runtime__/', '');
    const runtimePath = path.join(__dirname, '__runtime__', runtimeFile);

    if (fs.existsSync(runtimePath)) {
      const ext = path.extname(runtimeFile);
      const contentType = MIME[ext] || 'application/javascript; charset=utf-8';

      res.writeHead(200, {
        'Content-Type': contentType,
        'Access-Control-Allow-Origin': '*',
        'Cache-Control': 'no-cache',
      });

      return fs.createReadStream(runtimePath).pipe(res);
    }

    log('warn', \`[RUNTIME] Not found: \${runtimeFile}\`);
    res.writeHead(404);
    return res.end('Runtime script not found');
  }

  // Serve index.html for root
  if (reqPath === '/' || reqPath === '/index.html') {
    stats.hits++;
    res.writeHead(200, {
      'Content-Type': 'text/html; charset=utf-8',
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Methods': '*',
      'Access-Control-Allow-Headers': '*',
    });
    return res.end(indexHtml);
  }

  // Look up in URL map (try full URL with query, then path only)
  const cached = lookup[req.url] || lookup[reqPath];

  if (cached) {
    const filePath = path.join(__dirname, cached.localFile);

    // Check if we have a patched version in memory
    if (patchCache.has(cached.localFile)) {
      stats.hits++;
      const patchedContent = patchCache.get(cached.localFile);

      const ext = path.extname(cached.localFile);
      const contentType = cached.contentType || MIME[ext] || 'application/octet-stream';

      res.writeHead(200, {
        'Content-Type': contentType,
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Methods': '*',
        'Access-Control-Allow-Headers': '*',
        'Cache-Control': 'public, max-age=31536000',
      });

      log('debug', \`[PATCHED] \${req.url} -> \${cached.localFile}\`);
      return res.end(patchedContent);
    }

    // Serve unpatched file if it exists
    if (fs.existsSync(filePath)) {
      stats.hits++;

      const ext = path.extname(cached.localFile);
      const contentType = cached.contentType || MIME[ext] || 'application/octet-stream';

      res.writeHead(200, {
        'Content-Type': contentType,
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Methods': '*',
        'Access-Control-Allow-Headers': '*',
        'Cache-Control': 'public, max-age=31536000',
      });

      log('debug', \`[HIT] \${req.url} -> \${cached.localFile}\`);
      return fs.createReadStream(filePath).pipe(res);
    }
  }

  // Try proxying to original server
  if (PROXY_ENABLED) {
    stats.misses++;

    // Construct full URL for proxying
    const fullUrl = originalUrlObj.origin + req.url;
    return proxyRequest(fullUrl, res);
  }

  // SPA fallback for HTML routes
  if (!reqPath.includes('.')) {
    res.writeHead(200, {
      'Content-Type': 'text/html; charset=utf-8',
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Methods': '*',
      'Access-Control-Allow-Headers': '*',
    });
    return res.end(indexHtml);
  }

  // 404
  stats.misses++;
  log('info', \`[MISS] \${req.url}\`);
  res.writeHead(404, {
    'Access-Control-Allow-Origin': '*',
  });
  res.end('Not found');
}).listen(PORT, () => {
  console.log('');
  console.log('='.repeat(60));
  console.log('  VISUAL CLONER SERVER');
  console.log('='.repeat(60));
  console.log('');
  console.log('  URL:          http://localhost:' + PORT);
  console.log('  Original:     ' + ORIGINAL_URL);
  console.log('  Resources:    ' + Object.keys(urlMap).length);
  console.log('  Patched:      ' + stats.patched + ' file(s)');
  console.log('  Proxy:        ' + (PROXY_ENABLED ? 'Enabled' : 'Disabled'));
  console.log('  Runtime:      http://localhost:' + PORT + '/__runtime__/');
  console.log('  Status:       http://localhost:' + PORT + '/__status__');
  console.log('');
  console.log('  Press Ctrl+C to stop');
  console.log('');
});
`;
}

export default { generateServer };
